name: Continuous Integration

on:
  push:
  pull_request:
    branches:
      - "*"

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checks
        run: |
          npm ci
          npm run format
          npm run type-check
          npm run lint
  jest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Jest
        run: |
          npm ci
          npm run test:ci
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm run preview
